pyDKB/logging: add suffix alignment for traceback messages.
Looks this way:
```
2018-07-06 11:52:58,540: (DEBUG) Traceback info: (pyDKB)
  (==) Traceback (most recent call last):                       (pyDKB)
  (==)   File "pyDKB/__init__.py", line 24, in <module>         (pyDKB)
  (==)     import dataflow                                      (pyDKB)
  (==)   File "pyDKB/dataflow/__init__.py", line 6, in <module> (pyDKB)
  (==)     from dkbID import dkbIDs                             (pyDKB)
  (==) ImportError: cannot import name dkbIDs                   (pyDKB)
```

...instead of:
```
2018-07-06 11:52:58,540: (DEBUG) Traceback info: (pyDKB)
  (==) Traceback (most recent call last): (pyDKB)
  (==)   File "pyDKB/__init__.py", line 24, in <module> (pyDKB)
  (==)     import dataflow (pyDKB)
  (==)   File "pyDKB/dataflow/__init__.py", line 6, in <module> (pyDKB)
  (==)     from dkbID import dkbIDs (pyDKB)
  (==) ImportError: cannot import name dkbIDs (pyDKB)
```